plugin:
    name: 'webmors.twilio::lang.plugin.name'
    description: 'webmors.twilio::lang.plugin.description'
    author: Webmors
    icon: oc-icon-qrcode
    homepage: ''
permissions:
    can-smstwilio:
        tab: can-smstwilio
        label: can-smstwilio
